# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Alex/Documents/КГ/lab_03/design.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(908, 701)
        MainWindow.setMinimumSize(QtCore.QSize(908, 701))
        MainWindow.setMaximumSize(QtCore.QSize(908, 701))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBoxChooseAlg = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxChooseAlg.setMinimumSize(QtCore.QSize(196, 161))
        self.groupBoxChooseAlg.setMaximumSize(QtCore.QSize(196, 161))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBoxChooseAlg.setFont(font)
        self.groupBoxChooseAlg.setObjectName("groupBoxChooseAlg")
        self.radioButtonCDA = QtWidgets.QRadioButton(self.groupBoxChooseAlg)
        self.radioButtonCDA.setGeometry(QtCore.QRect(10, 30, 166, 20))
        self.radioButtonCDA.setChecked(True)
        self.radioButtonCDA.setObjectName("radioButtonCDA")
        self.radioButtonBresFloat = QtWidgets.QRadioButton(self.groupBoxChooseAlg)
        self.radioButtonBresFloat.setGeometry(QtCore.QRect(10, 50, 166, 20))
        self.radioButtonBresFloat.setObjectName("radioButtonBresFloat")
        self.radioButtonWu = QtWidgets.QRadioButton(self.groupBoxChooseAlg)
        self.radioButtonWu.setGeometry(QtCore.QRect(10, 110, 166, 20))
        self.radioButtonWu.setObjectName("radioButtonWu")
        self.radioButtonBresInt = QtWidgets.QRadioButton(self.groupBoxChooseAlg)
        self.radioButtonBresInt.setGeometry(QtCore.QRect(10, 70, 166, 20))
        self.radioButtonBresInt.setObjectName("radioButtonBresInt")
        self.radioButtonBresSmooth = QtWidgets.QRadioButton(self.groupBoxChooseAlg)
        self.radioButtonBresSmooth.setGeometry(QtCore.QRect(10, 90, 181, 20))
        self.radioButtonBresSmooth.setObjectName("radioButtonBresSmooth")
        self.radioButtonLib = QtWidgets.QRadioButton(self.groupBoxChooseAlg)
        self.radioButtonLib.setGeometry(QtCore.QRect(10, 130, 176, 20))
        self.radioButtonLib.setObjectName("radioButtonLib")
        self.verticalLayout.addWidget(self.groupBoxChooseAlg)
        self.groupBoxChooseColour = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxChooseColour.setMinimumSize(QtCore.QSize(196, 86))
        self.groupBoxChooseColour.setMaximumSize(QtCore.QSize(196, 86))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBoxChooseColour.setFont(font)
        self.groupBoxChooseColour.setObjectName("groupBoxChooseColour")
        self.radioButtonBlack = QtWidgets.QRadioButton(self.groupBoxChooseColour)
        self.radioButtonBlack.setGeometry(QtCore.QRect(10, 30, 176, 20))
        self.radioButtonBlack.setChecked(True)
        self.radioButtonBlack.setObjectName("radioButtonBlack")
        self.radioButtonWhite = QtWidgets.QRadioButton(self.groupBoxChooseColour)
        self.radioButtonWhite.setGeometry(QtCore.QRect(10, 55, 176, 20))
        self.radioButtonWhite.setChecked(False)
        self.radioButtonWhite.setObjectName("radioButtonWhite")
        self.verticalLayout.addWidget(self.groupBoxChooseColour)
        self.groupBoxDrawLine = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxDrawLine.setMinimumSize(QtCore.QSize(196, 156))
        self.groupBoxDrawLine.setMaximumSize(QtCore.QSize(196, 156))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBoxDrawLine.setFont(font)
        self.groupBoxDrawLine.setObjectName("groupBoxDrawLine")
        self.lineEditStartX = QtWidgets.QLineEdit(self.groupBoxDrawLine)
        self.lineEditStartX.setGeometry(QtCore.QRect(25, 50, 66, 21))
        self.lineEditStartX.setObjectName("lineEditStartX")
        self.labelStartCoords = QtWidgets.QLabel(self.groupBoxDrawLine)
        self.labelStartCoords.setGeometry(QtCore.QRect(10, 30, 176, 16))
        self.labelStartCoords.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStartCoords.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelStartCoords.setScaledContents(False)
        self.labelStartCoords.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStartCoords.setObjectName("labelStartCoords")
        self.labelStartX = QtWidgets.QLabel(self.groupBoxDrawLine)
        self.labelStartX.setGeometry(QtCore.QRect(5, 50, 16, 21))
        self.labelStartX.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStartX.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelStartX.setScaledContents(False)
        self.labelStartX.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStartX.setObjectName("labelStartX")
        self.labelStartY = QtWidgets.QLabel(self.groupBoxDrawLine)
        self.labelStartY.setGeometry(QtCore.QRect(100, 50, 16, 21))
        self.labelStartY.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelStartY.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelStartY.setScaledContents(False)
        self.labelStartY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStartY.setObjectName("labelStartY")
        self.lineEditStartY = QtWidgets.QLineEdit(self.groupBoxDrawLine)
        self.lineEditStartY.setGeometry(QtCore.QRect(120, 50, 66, 21))
        self.lineEditStartY.setObjectName("lineEditStartY")
        self.labelEndX = QtWidgets.QLabel(self.groupBoxDrawLine)
        self.labelEndX.setGeometry(QtCore.QRect(5, 95, 16, 21))
        self.labelEndX.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelEndX.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelEndX.setScaledContents(False)
        self.labelEndX.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEndX.setObjectName("labelEndX")
        self.lineEditEndX = QtWidgets.QLineEdit(self.groupBoxDrawLine)
        self.lineEditEndX.setGeometry(QtCore.QRect(25, 95, 66, 21))
        self.lineEditEndX.setObjectName("lineEditEndX")
        self.labelEndCoords = QtWidgets.QLabel(self.groupBoxDrawLine)
        self.labelEndCoords.setGeometry(QtCore.QRect(10, 75, 176, 16))
        self.labelEndCoords.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelEndCoords.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelEndCoords.setScaledContents(False)
        self.labelEndCoords.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEndCoords.setObjectName("labelEndCoords")
        self.lineEditEndY = QtWidgets.QLineEdit(self.groupBoxDrawLine)
        self.lineEditEndY.setGeometry(QtCore.QRect(120, 95, 66, 21))
        self.lineEditEndY.setObjectName("lineEditEndY")
        self.labelEndY = QtWidgets.QLabel(self.groupBoxDrawLine)
        self.labelEndY.setGeometry(QtCore.QRect(100, 95, 16, 21))
        self.labelEndY.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelEndY.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelEndY.setScaledContents(False)
        self.labelEndY.setAlignment(QtCore.Qt.AlignCenter)
        self.labelEndY.setObjectName("labelEndY")
        self.pushButtonDrawLine = QtWidgets.QPushButton(self.groupBoxDrawLine)
        self.pushButtonDrawLine.setGeometry(QtCore.QRect(2, 120, 191, 32))
        self.pushButtonDrawLine.setObjectName("pushButtonDrawLine")
        self.verticalLayout.addWidget(self.groupBoxDrawLine)
        self.groupBoxDrawSpectrum = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxDrawSpectrum.setMinimumSize(QtCore.QSize(196, 111))
        self.groupBoxDrawSpectrum.setMaximumSize(QtCore.QSize(196, 111))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBoxDrawSpectrum.setFont(font)
        self.groupBoxDrawSpectrum.setObjectName("groupBoxDrawSpectrum")
        self.lineEditAngle = QtWidgets.QLineEdit(self.groupBoxDrawSpectrum)
        self.lineEditAngle.setGeometry(QtCore.QRect(10, 50, 176, 21))
        self.lineEditAngle.setObjectName("lineEditAngle")
        self.labelAngle = QtWidgets.QLabel(self.groupBoxDrawSpectrum)
        self.labelAngle.setGeometry(QtCore.QRect(10, 30, 176, 16))
        self.labelAngle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelAngle.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelAngle.setScaledContents(False)
        self.labelAngle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAngle.setObjectName("labelAngle")
        self.pushButtonDrawSpectrum = QtWidgets.QPushButton(self.groupBoxDrawSpectrum)
        self.pushButtonDrawSpectrum.setGeometry(QtCore.QRect(2, 75, 191, 32))
        self.pushButtonDrawSpectrum.setObjectName("pushButtonDrawSpectrum")
        self.verticalLayout.addWidget(self.groupBoxDrawSpectrum)
        self.groupBoxResearch = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxResearch.setMinimumSize(QtCore.QSize(196, 122))
        self.groupBoxResearch.setMaximumSize(QtCore.QSize(196, 122))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBoxResearch.setFont(font)
        self.groupBoxResearch.setObjectName("groupBoxResearch")
        self.lineEditLineLen = QtWidgets.QLineEdit(self.groupBoxResearch)
        self.lineEditLineLen.setGeometry(QtCore.QRect(100, 30, 86, 21))
        self.lineEditLineLen.setObjectName("lineEditLineLen")
        self.labelLineLen = QtWidgets.QLabel(self.groupBoxResearch)
        self.labelLineLen.setGeometry(QtCore.QRect(10, 30, 86, 21))
        self.labelLineLen.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelLineLen.setFrameShadow(QtWidgets.QFrame.Plain)
        self.labelLineLen.setScaledContents(False)
        self.labelLineLen.setAlignment(QtCore.Qt.AlignCenter)
        self.labelLineLen.setObjectName("labelLineLen")
        self.pushButtonTimeComp = QtWidgets.QPushButton(self.groupBoxResearch)
        self.pushButtonTimeComp.setGeometry(QtCore.QRect(2, 55, 191, 32))
        self.pushButtonTimeComp.setObjectName("pushButtonTimeComp")
        self.pushButtonStepComp = QtWidgets.QPushButton(self.groupBoxResearch)
        self.pushButtonStepComp.setGeometry(QtCore.QRect(2, 85, 191, 32))
        self.pushButtonStepComp.setObjectName("pushButtonStepComp")
        self.verticalLayout.addWidget(self.groupBoxResearch)
        self.pushButtonScreenClean = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonScreenClean.setObjectName("pushButtonScreenClean")
        self.verticalLayout.addWidget(self.pushButtonScreenClean)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.graphicsView.setLineWidth(1)
        self.graphicsView.setMidLineWidth(0)
        self.graphicsView.setInteractive(False)
        self.graphicsView.setViewportUpdateMode(QtWidgets.QGraphicsView.SmartViewportUpdate)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEditStartX, self.lineEditStartY)
        MainWindow.setTabOrder(self.lineEditStartY, self.lineEditEndX)
        MainWindow.setTabOrder(self.lineEditEndX, self.lineEditEndY)
        MainWindow.setTabOrder(self.lineEditEndY, self.lineEditAngle)
        MainWindow.setTabOrder(self.lineEditAngle, self.lineEditLineLen)
        MainWindow.setTabOrder(self.lineEditLineLen, self.radioButtonCDA)
        MainWindow.setTabOrder(self.radioButtonCDA, self.radioButtonWhite)
        MainWindow.setTabOrder(self.radioButtonWhite, self.radioButtonBlack)
        MainWindow.setTabOrder(self.radioButtonBlack, self.radioButtonBresFloat)
        MainWindow.setTabOrder(self.radioButtonBresFloat, self.radioButtonWu)
        MainWindow.setTabOrder(self.radioButtonWu, self.radioButtonBresInt)
        MainWindow.setTabOrder(self.radioButtonBresInt, self.pushButtonDrawLine)
        MainWindow.setTabOrder(self.pushButtonDrawLine, self.radioButtonBresSmooth)
        MainWindow.setTabOrder(self.radioButtonBresSmooth, self.pushButtonDrawSpectrum)
        MainWindow.setTabOrder(self.pushButtonDrawSpectrum, self.radioButtonLib)
        MainWindow.setTabOrder(self.radioButtonLib, self.pushButtonTimeComp)
        MainWindow.setTabOrder(self.pushButtonTimeComp, self.pushButtonStepComp)
        MainWindow.setTabOrder(self.pushButtonStepComp, self.pushButtonScreenClean)
        MainWindow.setTabOrder(self.pushButtonScreenClean, self.graphicsView)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторная работа №3"))
        self.groupBoxChooseAlg.setTitle(_translate("MainWindow", "Выбор алгоритма"))
        self.radioButtonCDA.setText(_translate("MainWindow", "ЦДА"))
        self.radioButtonBresFloat.setText(_translate("MainWindow", "Брезенхем (float)"))
        self.radioButtonWu.setText(_translate("MainWindow", "Ву"))
        self.radioButtonBresInt.setText(_translate("MainWindow", "Брезенхем (int)"))
        self.radioButtonBresSmooth.setText(_translate("MainWindow", "Брезенхем сглаживание"))
        self.radioButtonLib.setText(_translate("MainWindow", "Библиотечная функция"))
        self.groupBoxChooseColour.setTitle(_translate("MainWindow", "Выбор цвета линии"))
        self.radioButtonBlack.setText(_translate("MainWindow", "Чёрный"))
        self.radioButtonWhite.setText(_translate("MainWindow", "Белый"))
        self.groupBoxDrawLine.setTitle(_translate("MainWindow", "Построение отрезка"))
        self.lineEditStartX.setText(_translate("MainWindow", "0.0"))
        self.labelStartCoords.setText(_translate("MainWindow", "Начало отрезка"))
        self.labelStartX.setText(_translate("MainWindow", "X:"))
        self.labelStartY.setText(_translate("MainWindow", "Y:"))
        self.lineEditStartY.setText(_translate("MainWindow", "0.0"))
        self.labelEndX.setText(_translate("MainWindow", "X:"))
        self.lineEditEndX.setText(_translate("MainWindow", "141.422"))
        self.labelEndCoords.setText(_translate("MainWindow", "Конец отрезка"))
        self.lineEditEndY.setText(_translate("MainWindow", "141.422"))
        self.labelEndY.setText(_translate("MainWindow", "Y:"))
        self.pushButtonDrawLine.setText(_translate("MainWindow", "Построить"))
        self.groupBoxDrawSpectrum.setTitle(_translate("MainWindow", "Построение спектра"))
        self.lineEditAngle.setText(_translate("MainWindow", "10"))
        self.labelAngle.setText(_translate("MainWindow", "Угол поворота в градусах"))
        self.pushButtonDrawSpectrum.setText(_translate("MainWindow", "Построить"))
        self.groupBoxResearch.setTitle(_translate("MainWindow", "Исследования"))
        self.lineEditLineLen.setText(_translate("MainWindow", "10"))
        self.labelLineLen.setText(_translate("MainWindow", "Длина линии:"))
        self.pushButtonTimeComp.setText(_translate("MainWindow", "Сравнение времени"))
        self.pushButtonStepComp.setText(_translate("MainWindow", "Сравнение ступенчатости"))
        self.pushButtonScreenClean.setText(_translate("MainWindow", "Очистить экран"))
