# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/Alex/Documents/КГ/lab_01/design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(900, 700))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(175, 193))
        self.groupBox.setMaximumSize(QtCore.QSize(175, 190))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_x = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_x.setGeometry(QtCore.QRect(10, 40, 71, 21))
        self.lineEdit_x.setObjectName("lineEdit_x")
        self.lineEdit_y = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_y.setGeometry(QtCore.QRect(90, 40, 71, 21))
        self.lineEdit_y.setObjectName("lineEdit_y")
        self.label_x = QtWidgets.QLabel(self.groupBox)
        self.label_x.setGeometry(QtCore.QRect(40, 20, 20, 20))
        self.label_x.setAutoFillBackground(False)
        self.label_x.setObjectName("label_x")
        self.label_y = QtWidgets.QLabel(self.groupBox)
        self.label_y.setGeometry(QtCore.QRect(120, 20, 20, 20))
        self.label_y.setAutoFillBackground(False)
        self.label_y.setObjectName("label_y")
        self.pushButton_add_1 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_add_1.setGeometry(QtCore.QRect(0, 100, 171, 32))
        self.pushButton_add_1.setObjectName("pushButton_add_1")
        self.pushButton_add_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_add_2.setGeometry(QtCore.QRect(0, 130, 171, 32))
        self.pushButton_add_2.setObjectName("pushButton_add_2")
        self.pushButton_clear_xy = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_clear_xy.setGeometry(QtCore.QRect(0, 70, 171, 32))
        self.pushButton_clear_xy.setObjectName("pushButton_clear_xy")
        self.pushButton_change_point = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_change_point.setEnabled(False)
        self.pushButton_change_point.setGeometry(QtCore.QRect(0, 160, 171, 32))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_change_point.setFont(font)
        self.pushButton_change_point.setObjectName("pushButton_change_point")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(175, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listWidget_1 = QtWidgets.QListWidget(self.groupBox_2)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.listWidget_1.setPalette(palette)
        self.listWidget_1.setAutoFillBackground(False)
        self.listWidget_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_1.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidget_1.setObjectName("listWidget_1")
        self.verticalLayout_3.addWidget(self.listWidget_1)
        self.pushButton_rem_point_1 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_rem_point_1.setEnabled(False)
        self.pushButton_rem_point_1.setObjectName("pushButton_rem_point_1")
        self.verticalLayout_3.addWidget(self.pushButton_rem_point_1)
        self.pushButton_rem_all_points_1 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_rem_all_points_1.setEnabled(False)
        self.pushButton_rem_all_points_1.setObjectName("pushButton_rem_all_points_1")
        self.verticalLayout_3.addWidget(self.pushButton_rem_all_points_1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(175, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(175, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(128, 0, 128, 26))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(128, 0, 128, 24))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.listWidget_2.setPalette(palette)
        self.listWidget_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_4.addWidget(self.listWidget_2)
        self.pushButton_rem_point_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_rem_point_2.setEnabled(False)
        self.pushButton_rem_point_2.setObjectName("pushButton_rem_point_2")
        self.verticalLayout_4.addWidget(self.pushButton_rem_point_2)
        self.pushButton_rem_all_points_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_rem_all_points_2.setEnabled(False)
        self.pushButton_rem_all_points_2.setObjectName("pushButton_rem_all_points_2")
        self.verticalLayout_4.addWidget(self.pushButton_rem_all_points_2)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_info_graph = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_info_graph.sizePolicy().hasHeightForWidth())
        self.label_info_graph.setSizePolicy(sizePolicy)
        self.label_info_graph.setMinimumSize(QtCore.QSize(191, 20))
        self.label_info_graph.setAutoFillBackground(False)
        self.label_info_graph.setObjectName("label_info_graph")
        self.verticalLayout.addWidget(self.label_info_graph)
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setMinimumSize(QtCore.QSize(601, 531))
        self.graphicsView.setAutoFillBackground(False)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setRenderHints(QtGui.QPainter.Antialiasing|QtGui.QPainter.HighQualityAntialiasing|QtGui.QPainter.TextAntialiasing)
        self.graphicsView.setViewportUpdateMode(QtWidgets.QGraphicsView.FullViewportUpdate)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_get_ans = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_get_ans.sizePolicy().hasHeightForWidth())
        self.pushButton_get_ans.setSizePolicy(sizePolicy)
        self.pushButton_get_ans.setMinimumSize(QtCore.QSize(160, 70))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_get_ans.setFont(font)
        self.pushButton_get_ans.setAutoDefault(False)
        self.pushButton_get_ans.setDefault(False)
        self.pushButton_get_ans.setFlat(False)
        self.pushButton_get_ans.setObjectName("pushButton_get_ans")
        self.horizontalLayout.addWidget(self.pushButton_get_ans)
        self.label_info_ans = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_info_ans.sizePolicy().hasHeightForWidth())
        self.label_info_ans.setSizePolicy(sizePolicy)
        self.label_info_ans.setMinimumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_info_ans.setFont(font)
        self.label_info_ans.setAutoFillBackground(False)
        self.label_info_ans.setObjectName("label_info_ans")
        self.horizontalLayout.addWidget(self.label_info_ans)
        self.listWidget_ans = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget_ans.sizePolicy().hasHeightForWidth())
        self.listWidget_ans.setSizePolicy(sizePolicy)
        self.listWidget_ans.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_ans.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget_ans.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidget_ans.setObjectName("listWidget_ans")
        self.horizontalLayout.addWidget(self.listWidget_ans)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Лабораторная работа №1"))
        self.groupBox.setTitle(_translate("MainWindow", "Ввод  координат точки"))
        self.label_x.setText(_translate("MainWindow", "X"))
        self.label_y.setText(_translate("MainWindow", "Y"))
        self.pushButton_add_1.setText(_translate("MainWindow", "Добавить в мн-во №1"))
        self.pushButton_add_2.setText(_translate("MainWindow", "Добавить в мн-во №2"))
        self.pushButton_clear_xy.setText(_translate("MainWindow", "Очистить поля ввода"))
        self.pushButton_change_point.setText(_translate("MainWindow", "Заменить выбранную точку"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Множество №1"))
        self.pushButton_rem_point_1.setText(_translate("MainWindow", "Удалить точку"))
        self.pushButton_rem_all_points_1.setText(_translate("MainWindow", "Удалить все точки"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Множество №2"))
        self.pushButton_rem_point_2.setText(_translate("MainWindow", "Удалить точку"))
        self.pushButton_rem_all_points_2.setText(_translate("MainWindow", "Удалить все точки"))
        self.label_info_graph.setText(_translate("MainWindow", "Графическое представление:"))
        self.pushButton_get_ans.setText(_translate("MainWindow", "Решить"))
        self.label_info_ans.setText(_translate("MainWindow", "Ответ:"))
